camera:
  resolution_width: 848
  resolution_height: 480
  fps: 30
plc:
  ip: "192.168.1.165"
  port: 5010
  start_d_reg: 1001
paths:
  template_dir: "data/templates"     # เก็บรูป Template และ Offset
  save_dir: "data/logs"              # เก็บไฟล์ 3D Point Cloud ตอนทดสอบ
  position_mem: "data/logs/position_mem.json"
app:
  timer_lock_seconds: 0.5
  frames_for_averaging: 70